[project]
name = "plugin"
keywords = ["framework"]
version = "0.1.0b3"
description = "A Ballsdex package framework for providing extra capabilities to other packages."
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Cayla", email = "official.dotzz@gmail.com" },
]
requires-python = ">=3.13"
readme = "README.md"

[dependency-groups]
dev = [
    "bd-stubs[all]",
    "ruff>=0.16.10",
]

docs = [
    "markdown-grid-tables>=0.6.0",
    "mkdocs-material>=9.7.7",
    "mkdocstrings[python]>=1.0.6",
]

[tool.pyright]
reportMissingModuleSource = "none"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["ballsdex", "bd_models", "settings"]
split-on-trailing-comma = false

[tool.uv.sources]
bd-stubs = { git = "https://github.com/Caylies/bd-stubs", rev = "0.1.2" }

[project.urls]
Homepage = "https://caylies.github.io/Plugin/"
Documentation = "https://caylies.github.io/Plugin/"
Changelogs = "https://caylies.github.io/Plugin/changelog"
Funding = "https://ko-fi.com/caylies"
